name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Santiago

          config_order: base.header, isocalendar, languages, achievements
          
          plugin_languages: yes
          plugin_languages_other: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_achievements_display: compact
